# Generated by Django 5.1.2 on 2024-10-28 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wallTexture', models.ImageField(upload_to='textures')),
                ('floorTexture', models.ImageField(upload_to='textures')),
                ('cellingTexture', models.ImageField(upload_to='textures')),
                ('scale', models.JSONField()),
                ('access', models.CharField(choices=[('PRIVATE', 'private'), ('PUBLIC', 'public')], default='PUBLIC', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('art', models.FileField(upload_to='arts')),
                ('price', models.IntegerField(max_length=10)),
                ('author', models.CharField(max_length=50)),
                ('position', models.JSONField()),
                ('rotation', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.gallery')),
            ],
        ),
    ]
