# Generated by Django 5.1.2 on 2024-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gallery_balance_alter_arts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='author',
            field=models.CharField(default='Author', max_length=50),
        ),
    ]
